services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - .:/app
